# Generated by Django 5.1.2 on 2025-11-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveIntegerField(unique=True)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'В работе'), ('approved', 'Утверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('current_step_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('approver_name', models.CharField(max_length=100)),
                ('approver_role', models.CharField(blank=True, max_length=150)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('skipped', 'Пропущено')], default='waiting', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals_app.approvalchain')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
