# Generated by Django 5.1.2 on 2025-11-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(help_text='Telegram ID автора заявки (user.id)')),
                ('author_username', models.CharField(blank=True, help_text='Telegram username автора (@username), если есть', max_length=150)),
                ('author_full_name', models.CharField(blank=True, help_text='Отображаемое имя автора в Telegram', max_length=255)),
                ('warehouse', models.CharField(help_text="Склад: например, 'Алматы' или 'Капчагай'", max_length=50)),
                ('category', models.CharField(help_text="Категория расходов: 'Авто', 'Аренда', ...", max_length=100)),
                ('subcategory', models.CharField(help_text="Подкатегория / статья расходов: 'Ремонт авто', 'ГСМ', ...", max_length=150)),
                ('subsubcategory', models.CharField(blank=True, help_text="Подподкатегория: 'Газели', '5 тонник', 'Фавы', 'Другое' и т.п.", max_length=150)),
                ('extra_value', models.CharField(blank=True, help_text='Доп. значение: номер авто, что и для чего приобретается и т.п.', max_length=255)),
                ('goal', models.CharField(blank=True, help_text="Цель закупа: 'Пополнение ГСМ', 'Оплата аренды' и т.п.", max_length=255)),
                ('item_name', models.CharField(blank=True, help_text="Что закупается: 'АЙ-92', 'услуги охраны', 'пакеты' и т.д.", max_length=255)),
                ('quantity', models.CharField(blank=True, help_text="Количество (можно хранить строкой: '1', '50 шт', 'по 3 шт' и т.п.)", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма закупа', max_digits=14)),
                ('comment', models.TextField(blank=True, help_text='Комментарий автора (может быть обязателен для некоторых статей)')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'На согласовании'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('paid', 'Оплачена')], default='new', help_text='Текущий статус заявки', max_length=20)),
                ('current_level', models.PositiveSmallIntegerField(default=0, help_text='Текущий уровень согласования (0 - ещё не отправлено на согласование)')),
                ('google_row_id', models.CharField(blank=True, help_text='Идентификатор строки в Google Sheets (если нужно)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='Публичный или полу-публичный URL файла (Google Drive / S3 и т.п.)')),
                ('storage_path', models.CharField(help_text='Путь в хранилище: /Категория/Подкатегория/Год-Месяц/Файл_№ID.pdf', max_length=255)),
                ('file_name', models.CharField(help_text='Имя файла', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда файл был загружен')),
                ('request', models.ForeignKey(help_text='Заявка, к которой относится файл', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.request')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
            },
        ),
    ]
